import type { Metadata } from "next";
import Link from "next/link";
import { Poppins } from "next/font/google";
import { ChartColumnBigIcon } from "lucide-react";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { Button } from "@/components/ui/button";
import UserDropdown from "@/components/user-dropdown";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link
              href={"/"}
              className="font-bold text-2xl flex items-center gap-2"
            >
              <ChartColumnBigIcon className="text-lime-500" /> NextCash
            </Link>
            <div>
              <SignedOut>
                <div className="flex items-center">
                  <Button asChild variant={"link"} className="text-white">
                    <SignInButton />
                  </Button>
                  <Button asChild variant={"link"} className="text-white">
                    <SignUpButton />
                  </Button>
                </div>
              </SignedOut>
              <SignedIn>
                <UserDropdown />
              </SignedIn>
            </div>
          </nav>
          {children}
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
