import type { Metadata } from "next";
import Link from "next/link";
import { Poppins } from "next/font/google";
import { ChartColumnBigIcon } from "lucide-react";
import { ClerkProvider, SignedOut, SignInButton, SignUpButton } from "@clerk/nextjs";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link
              href={"/"}
              className="font-bold text-2xl flex items-center gap-2"
            >
              <ChartColumnBigIcon className="text-lime-500" /> NextCash
            </Link>
            <div>
              <SignedOut>
                <div className="flex items-center">
                  <SignInButton />
                  <SignUpButton />
                </div>
              </SignedOut>
            </div>
          </nav>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
